// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using outer_space.Data;

#nullable disable

namespace outer_space.Data.Migrations
{
    [DbContext(typeof(DataModelDbContext))]
    [Migration("20240202173330_Migration004-AddAstronautsAndMissions")]
    partial class Migration004AddAstronautsAndMissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("outer_space.Data.Tables.Astronaut", b =>
                {
                    b.Property<int>("AstronautID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AstronautID"));

                    b.Property<DateTime?>("AstornautDeathDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AstronautBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AstronautNameFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AstronautNameLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AstronautID");

                    b.ToTable("Astronauts");
                });

            modelBuilder.Entity("outer_space.Data.Tables.Galaxy", b =>
                {
                    b.Property<int>("GalaxyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalaxyID"));

                    b.Property<string>("GalaxyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GalaxyDiameterInParsecs")
                        .HasColumnType("int");

                    b.Property<string>("GalaxyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalaxyID");

                    b.ToTable("Galaxies");
                });

            modelBuilder.Entity("outer_space.Data.Tables.Mission", b =>
                {
                    b.Property<int>("MissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionID"));

                    b.Property<DateTime?>("MissionDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MissionDateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MissionID");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("outer_space.Data.Tables.MissionAstronaut", b =>
                {
                    b.Property<int>("MissionID")
                        .HasColumnType("int");

                    b.Property<int>("AstronautID")
                        .HasColumnType("int");

                    b.Property<string>("MissionAstronautRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MissionID", "AstronautID");

                    b.HasIndex("AstronautID");

                    b.ToTable("MissionAstronauts");
                });

            modelBuilder.Entity("outer_space.Data.Tables.MissionAstronaut", b =>
                {
                    b.HasOne("outer_space.Data.Tables.Astronaut", "Astronaut")
                        .WithMany("MissionAstronauts")
                        .HasForeignKey("AstronautID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("outer_space.Data.Tables.Mission", "Mission")
                        .WithMany("MissionAstronauts")
                        .HasForeignKey("MissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("outer_space.Data.Tables.Astronaut", b =>
                {
                    b.Navigation("MissionAstronauts");
                });

            modelBuilder.Entity("outer_space.Data.Tables.Mission", b =>
                {
                    b.Navigation("MissionAstronauts");
                });
#pragma warning restore 612, 618
        }
    }
}
